---
celeste_path: C:\Program Files (x86)\Steam\steamapps\common\Celeste
exit_game_when_done: true
clear_output_log_on_startup: true

# How many lines to trim off the start and end respectively of Celeste.tas
# Useful for ignoring chapter restarts, S&Qs, getting to the chapter complete screen, etc.
input_file_trims:
  - 7
  - 1

# When starting the program or unpausing, wait this many seconds to give time for switching focus to Celeste
initial_delay_time: 5

# Note that pausing only actually starts when the TAS completes
# Be sure to pause only when the TAS is running, and hold the pause key for a bit
# Once it says "Pause key pressed" you can safely alt-tab
pause_key: "0"  # That's zero

# Whether to randomize the order of attempted lines, or to go sequentially
random_order: true

# Make sure that .tas files are assigned to a text editor (Windows only)
  open_celeste_tas_when_done: true

# Used to track if the TAS is still running by looking at Celeste Studio's CPU usage
# Don't touch unless you know what you're doing (ask Kataiser if you're having problems)
studio_cpu_threshold: 10
studio_cpu_interval: 0.2
studio_cpu_consecutive: 5
studio_cpu_timeout: 40
