---
celeste_path: C:\Program Files (x86)\Steam\steamapps\common\Celeste

# When starting the program or unpausing, wait this many seconds to give time for switching focus to Celeste
initial_delay_time: 5

# Note that pausing only actually starts when the TAS completes
# Be sure to pause only when the TAS is running and hold the pause key for at least 0.1 seconds (sorry)
pause_key: O

exit_game_when_done: true

# Whether to randomize the order of attempted lines, or to go sequentially
random_order: true

# How many lines to trim off the start and end respectively of Celeste.tas
# Useful for ignoring chapter restarts, S&Qs, getting to the chapter complete screen, etc.
input_file_trims:
  - 7
  - 1

# Used to track if the TAS is still running by looking at Celeste Studio's CPU usage
studio_cpu_threshold: 10
studio_cpu_interval: 0.1
