---
celeste_path: C:\Program Files (x86)\Steam\steamapps\common\Celeste
clear_output_log_on_startup: true

# How many lines to trim off the start and end respectively of Celeste.tas
# Useful for ignoring chapter restarts, S&Qs, getting to the chapter complete screen, etc.
input_file_trims:
  - 7
  - 1

# When starting the program or unpausing, wait this many seconds to give time for switching focus to Celeste
initial_delay_time: 5

# Note that pausing only actually starts when the TAS completes
# Be sure to pause only when the TAS is running, and hold the pause key for a bit
# Once it says "Pause key pressed" you can safely alt-tab
pause_key: "0"  # That's zero

# Can be forward, reverse, or random
order: random

# whether the TAS file uses console load to start, or restart chapter
console_load_mode: false

# Everest has a delay when loading level complete screen textures for custom maps,
# so wait this many seconds for that (5 is recommended)
loading_time_compensation: 0

# Also closes Studio
exit_game_when_done: true

# Make sure that .tas files are assigned to a text editor (Windows only)
open_celeste_tas_when_done: true

# Do some extra optimization attempts when done
extra_attempts: true
extra_attempts_window_size: 5

# Whether to wait until the Celeste window is focused, and if not, how many minutes to wait before giving up
keep_celeste_focused: true
focus_wait_timeout: 3

# Used to track if the TAS is still running, using Everest's DebugRC server
# Don't touch unless you know what you're doing (ask Kataiser if you're having problems)
session_consecutive: 2
session_interval: 0.5
session_timeout: 40
