pos_init: 0
speed_init: 0
jump_timer: 0  # 11 if just jumped, 14 if wallbounced
jump_speed: 0  # -105 if just jumped, -160 if wallbounced, irrelevant if jump timer = 0
auto_jump: false  # forced half peak gravity, from dashes, springs, etc.
ducking: false
on_ground: false
cold_core: false
holding: false  # only applies to x axis
in_space: false

frames: 10
permutations: 100000
axis: 'x'  # which axis to process, x or y
goal_position: 1
goal_speed: 90  # this is calculated by |final speed - goal speed|
goal_direction: '-'  # - means approaching from the left/top, + is from the right/bottom
prioritize_speed: false  # sort by speed instead of position
append_keys: ''  # keys the formatter adds, e.g. "rg" to hold right and grab as well
open_results: true  # automatically opens the results file in the default text editor