frames: 15
permutations: 1000000
axis: 'x'  # which axis to process, x or y
goal_position: 160
goal_speed: 90  # this is calculated by |final speed - goal speed|
goal_direction: '-'  # - means approaching from the left/top, + is from the right/bottom
prioritize_speed: false  # sort by speed instead of position
append_keys: ''  # keys the formatter adds, e.g. "jg" to hold jump and grab as well
open_results: true  # automatically opens the results file in the default text editor

hide_duplicates: true  # don't output multiple inputs with the same resulting pos/speed (disable for performance)
silent_output: false  # enable to save inputs directly to the file, skipping console (enable for performance)
triangular_random: false  # bias toward shorter inputs, may improve precision (disable for performance)

jump_timer: 0  # 11 if just jumped, 14 if wallbounced
jump_speed: 0  # -105 if just jumped, -160 if wallbounced, irrelevant if jump timer = 0
auto_jump: false  # forced half peak gravity, from dashes, springs, etc.
ducking: false
on_ground: false
cold_core: false
holding: false  # only applies to x axis
in_space: false

# use control-shift-C in Studio and paste here
init_state: "
Pos: 160.458372503519,67.7499865889549
Speed: 0.00,-15.00
Vel: 0.00,0.00
Stamina: 110 Timer: 16.609
Dash 
[1]
"