# Use control-shift-C in Studio and paste here
init_state: "
Pos: 160.458372503519, 67.7499865889549
Speed: 0.00, -15.00
Vel: 0.00, 0.00
Stamina: 110 Timer: 16.609
Dash
[1]

AutoJump: False
MaxFall: 160.00
JumpTimer: 0
Holding:
"

# More init state, ignored if using custom info (except on_ground which is always manual)
# X axis
on_ground: false
holding: false
# Y axis
jump_timer: 0  # 11 if just jumped, 14 if wallbounced. jump speed will be based on current speed
auto_jump: false  # forced half peak gravity, from dashes, springs, etc.
max_fall: 160  # 160 if you aren't fast falling yet, current Y speed if you are. gets weird for a few frames after down dashes

# Target and processing
frames: 12
permutations: 1000000
axis: x  # which axis to process, x or y
goal_position: 160.5
goal_speed: 90  # this is calculated by |final speed - goal speed|
goal_direction: '-'  # '-' means approaching from the left/top, '+' is from the right/bottom
prioritize_speed: false  # sort by speed instead of position
disabled_key: auto  # disable generating a certain key, "auto" or blank will disable keys that can't ever affect input
rng_threshold: 20  # frame count to start using the RNG method when a key is disabled
rng_threshold_slow: 14  # for when all keys are being generated
triangular_random: false  # bias toward shorter inputs, may improve precision (disable for performance)
ram_check: true  # if generating inputs makes your PC run low on RAM, exit early

# Output
append_keys: ''  # keys the formatter adds, e.g. 'jg' to hold jump and grab as well
open_results: true  # automatically opens the results file in the default text editor
hide_duplicates: true  # don't output multiple inputs with the same resulting pos/speed (disable for performance)
silent_output: false  # enable to save inputs directly to the file, skipping console (enable for performance)
