---
tas_path: C:\Program Files (x86)\Steam\steamapps\common\Celeste\Celeste.tas
clear_output_log_on_startup: true
ensure_breakpoint_end: true
exit_game_when_done: false

# How many lines to trim off the start and end respectively of the file
# Useful for ignoring chapter restarts, S&Qs, getting to the chapter complete screen, etc.
# Note that this doesn't actually edit the file, just what Radeline uses
input_file_trims:
  - 0
  - 0

# Ignore the above setting and just trim based on "#Start" and the last empty line in the file
auto_trim: true

# Note that pausing only actually starts when the TAS completes
# Be sure to pause only when the TAS is running, and hold the pause key for a bit
# Once it says "Pause key pressed" you can safely alt-tab
pause_key: "0"  # That's zero

# Can be forward, reverse, or random
order: random

# Try to optimize feathers by adjusting their angles by a few degrees
# Can add up to quite a bit longer execution time with a high degree window
optimize_feathers: true
feather_degree_window_size: 2

# Everest has a delay when loading level complete screen textures for custom maps,
# so wait this many seconds for that (5 is recommended)
loading_time_compensation: 0

# Make sure that .tas files are assigned to a text editor (Windows only)
open_tas_when_done: true

# Do some extra optimization attempts when done
extra_attempts: true
extra_attempts_window_size: 5

# Whether to wait until the Celeste window is focused, and if not, how many minutes to wait before giving up
keep_celeste_focused: true
focus_wait_timeout: 3

# Used to track if the TAS is still running, using Everest's DebugRC server
# Don't touch unless you know what you're doing (ask Kataiser if you're having problems)
session_interval: 1
session_wait: 1
session_short_timeout: 2
session_long_timeout: 40
session_alt_timeout_method: false

# It's possible for the game to crash if you load custom maps too many times,
# so these are for trying to deal with that (waits are in seconds)
restart_crashed_game: true
restart_prewait: 15
restart_postwait: 60
kill_notepads: true
