name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.11.0
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.0
        architecture: 'x86'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build release package
      run: |
        python build.py
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Radeline
        path: Radeline
